config/routes.rb
Rails.application.routes.draw do
  get 'thzz' => 'thzz#index'
  get 'thzz/show' => 'thzz#show'
  get 'thzz/yz'
  get 'thzz/get' => 'thzz#index'
  post 'thzz/yz'
  post 'thzz/get' => 'thzz#create'
  get 'notice' => 'notice#index'

  resources :users

end

app/models/mobile_area.rb
class MobileArea
  include Mongoid::Document
  # 手机号前7位
  field :mobile, type: String
  # 省
  field :province, type: String
  # 城市名称
  field :cityname, type: String
  # 移动运营商
  field :isp, type: String

  validates :mobile, :province, :cityname, :isp, presence: true
  validates :mobile, uniqueness: true

end

app/models/user.rb
# encoding: utf-8

class User
  include Mongoid::Document
  include Mongoid::Timestamps
  paginates_per 50
  field :username, type: String
  field :mobile, type: String
  field :province, type: String
  field :cityname, type: String
  field :age, type: Integer
  field :sex, type: Integer
  field :sn, type: String
  field :used_at, type: Time
  default_scope -> { order( created_at: :desc ) }
  scope :not_used, -> { where(used_at: nil)}
  scope :used, -> { where(:used_at.ne =>  nil)}
  scope :not_used_by_time, ->(time) { where(:created_at.lt => time)}

  validates :mobile, :sn, presence: true
  validates :sn, format: { with: /\d{8}/ }
  validates :mobile,  uniqueness: { message: "你已经领取过，每人只能领取一次,请查收你的短信,或者联系我们" }
  validates :mobile, format: { with: /\A1[3|4|5|7|8][0-9]\d{8}\z/ , message: "手机号码输入不正确" }

  def gen_sn
    self.sn = rand(99999999)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notice_controller.rb
# encoding: utf-8
class NoticeController < ApplicationController

  def index
    @notice = "不好意思您来晚了，此活动已经领取完毕，请关注我们微信平台，第一时间获取更多优惠活动。"
  end

end

app/controllers/thzz_controller.rb
# encoding: utf-8

require "rest_client"

class ThzzController < ApplicationController

  def index
    @result = params[:result]
    @user = User.new
    @refer= params[:from]
  end

  def show
  end


  def create
    @user = User.new(user_params)
    @user.gen_sn
    if @user.save
      Rails.logger.debug send_sms_yunpian(@user.mobile,
                                          "【炭火制造】您的套餐领取码为:#{@user.sn}，进店请出示。地址:南公园步行街。电话:18609000625。")
      flash[:notice] = "恭喜你！[#{@user.mobile}]已经领取成功,请将此消息转发至朋友圈，并查收您的短信收件箱!"
      redirect_to action: 'index'
    else
      render action: :index
      return
    end
  end

  def yz
    @result = params[:result]
    if !params[:user]
      @user = User.new
      render action: 'yz'
      return
    end
    @user = User.find_by(sn: params[:user][:sn])
    if @user
      @user.used_at = Time.now
      if @user.save
        flash[:notice] = "验证成功"
        redirect_to action: 'yz', result: 'ok'
        return
      end
    end
    flash[:error] = "验证序列号不正确!"
    redirect_to action: 'yz', result: 'error'
  end

  private
  def user_params
    params[:user].permit(:mobile)
  end

  def send_sms_yunpian(mobile, text)
    #rails_config gem 配置
    apikey = Settings.yunpian.apikey
    url = Settings.yunpian.url
    RestClient.post(url,
                    apikey: apikey,
                    mobile: mobile,
                    text: text,
                    #content_type: :json,
                    accept: :json,
                    charset: 'utf-8')
  end

  def get_isp(mobile)
    url = "http://virtual.paipai.com/extinfo/GetMobileProductInfo?mobile=15850781443&amount=10000&callname=getPhoneNumInfoExtCallback"
    RestClient.get(url, accept: :json, charset: 'utf8')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "bobo", password: "lendlove"

  # GET /users
  # GET /users.json
  def index
    if params[:used] == "false"
      @users = User.not_used.page(params[:page])
    elsif params[:used] == "true"
      @users = User.used.page(params[:page])
    elsif params[:used] == "one_month_after"
      @users = User.not_used_by_time(1.month.ago).page(params[:page])
    else
      @users = User.all.page(params[:page])
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:username, :mobile, :age, :sex, :sn, :used_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/thzz_helper.rb
module ThzzHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <title>炭火制造烤鱼3折促销，268元烤鱼套餐只要98，数量有限速度来领!</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body class="bg">
      <%= yield %>
  </body>
</html>

app/views/notice/index.html.erb
<div class="row">
  <div class="col-xs-8 col-xs-offset-2 text-center mobile_input">
    <div class="alert alert-warning">
      <%= @notice %>
    </div>
    <%= link_to "返回上个活动", thzz_path, class: "btn btn-danger" %>
  </div>
  <style type="text/css" media="all">
  </style>
  <div class="col-xs-12 text-center">
    <div class="mt10">
      <%= image_tag("thzz_9.gif", class: "logo") %>
    </div>
    <div class="mt10">
      <div class="col-xs-6">
          <%= link_to image_tag("thzz_10.png", class: "logo"), notice_path %>
      </div>
      <div class="col-xs-6">
          <%= link_to image_tag("thzz_11.gif", class: "logo"), notice_path %>
      </div>
    </div>
    <div class="footer">
      @2015 行者网络 新ICP备15001313号 
      <script src="http://s11.cnzz.com/stat.php?id=1255151966&web_id=1255151966" language="JavaScript"></script>
    </div>
  </div>
</div>

app/views/thzz/_form.html.erb
<%= simple_form_for @user, url: thzz_get_path do |f| %>
  <%= f.input :mobile, label: false, placeholder: "请输入手机号", input_html: { class: ""} %>
  <%= button_to "", class: "btn btn-danger btn-block", data: { confirm: "此活动地址在昌吉市延安南路南公园步行街，确认要领取吗？" } do  %>
    <span class="glyphicon glyphicon-fire" aria-hidden="true"></span> 马上领取
  <% end %>
<% end %>
<%#<script>%>
  <%#$(document).ready(function () {%>
    <%#$("#new_user").validate({%>
      <%#debug: true,%>
      <%#rules: {%>
        <%#"user[mobile]": {required: true }%>
      <%#}%>
    <%#});%>
  <%#});%>
<%#</script>%>

app/views/thzz/index.html.erb
<div class="row">
  <%= image_tag("logo.png", class: "logo") %>
  <% if false  %>
    <%= image_tag("text3.png", class: "logo") %>
    <center>
      <%= image_tag("qr.jpg", class: "logo") %>
    </center>
  <% else %>
    <%= image_tag("thzz_1.png", class: "logo") %>
    <div class="col-xs-8 col-xs-offset-2 text-center mobile_input">
      <% if flash[:notice] %>
        <div class="alert alert-warning">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <%= render "form" %>
    </div>
  <% end %>
  <div class="col-xs-12 text-center">
    <div class="mt10">
      <%= image_tag("thzz_cd.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_2.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_3.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_4.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_5.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_6.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_7.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_8.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_9.png", class: "logo") %>
    </div>
    <div class="mt10">
      <div class="col-xs-6">
          <%= link_to image_tag("thzz_10.png", class: "logo"), notice_path %>
      </div>
      <div class="col-xs-6">
          <%= link_to image_tag("thzz_11.png", class: "logo"), notice_path %>
      </div>
    </div>
    <div class="footer">
      @2015 行者网络 新ICP备15001313号 
      <script src="http://s11.cnzz.com/stat.php?id=1255151966&web_id=1255151966" language="JavaScript"></script>
    </div>
  </div>
</div>

app/views/thzz/index1.html.erb
<div class="row">
  <%= image_tag("logo.png", class: "logo") %>
  <% if false  %>
    <%= image_tag("text3.png", class: "logo") %>
    <center>
      <%= image_tag("qr.jpg", class: "logo") %>
    </center>
  <% else %>
    <%= image_tag("thzz_1.png", class: "logo") %>
    <div class="col-xs-8 col-xs-offset-2 text-center mobile_input">
      <% if flash[:notice] %>
        <div class="alert alert-warning">
          <%= flash[:notice] %>
        </div>
      <% end %>
      <%= render "form" %>
    </div>
  <% end %>
  <div class="col-xs-12 text-center">
    <div class="mt10">
      <%= image_tag("thzz_cd.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_2.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_3.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_4.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_5.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_6.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_7.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_8.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_9.png", class: "logo") %>
    </div>
    <div class="mt10">
      <div class="col-xs-6">
          <%= link_to image_tag("thzz_10.png", class: "logo"), notice_path %>
      </div>
      <div class="col-xs-6">
          <%= link_to image_tag("thzz_11.png", class: "logo"), notice_path %>
      </div>
    </div>
    <div class="footer">
      @2015 行者网络 新ICP备15001313号 
      <script src="http://s11.cnzz.com/stat.php?id=1255151966&web_id=1255151966" language="JavaScript"></script>
    </div>
  </div>
</div>

app/views/thzz/show.html.erb
<div class="row">
  <%= image_tag("logo.png", class: "logo") %>
  <div class="col-xs-12 text-center">

    <div class="mt10" style="padding:20px" >
      <%= link_to(thzz_path,class: "btn btn-danger btn-block btn-lg")  do  %>
        <span class="glyphicon glyphicon-fire" aria-hidden="true"></span> 马上领取
      <% end %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_cd.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_2.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_3.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_4.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_5.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_6.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_7.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_8.png", class: "logo") %>
    </div>
    <div class="mt10">
      <%= image_tag("thzz_9.png", class: "logo") %>
    </div>
    <div class="mt10">
      <div class="col-xs-6">
        <%= link_to image_tag("thzz_10.png", class: "logo"), notice_path %>
      </div>
      <div class="col-xs-6">
        <%= link_to image_tag("thzz_11.png", class: "logo"), notice_path %>
      </div>
    </div>
    <div class="footer">
      @2015 行者网络 新ICP备15001313号 
      <script src="http://s11.cnzz.com/stat.php?id=1255151966&web_id=1255151966" language="JavaScript"></script>
    </div>
  </div>
</div>

app/views/thzz/yz.html.erb
<div class="container">

  <div class= "col-xs-10 col-xs-offset-1 text-center">

    <h1 style="padding: 20px">验证序列号</h1>
    <% if @result=="ok"  %>
      <h4><%= flash[:notice] %></h4>
    <% else %>
      <h4 class="error"><%= flash[:error] %></h4>
    <% end %>
    <%= simple_form_for @user, url: thzz_yz_path  do |f| %>
      <%= f.input :sn, label: false, placeholder: "序列号"  %>
      <%= f.submit value: "验证", class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= simple_form_for(@user, html: { class: "form-horizontal" }, wrapper: :horizontal_form) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :username %>
    <%= f.input :mobile %>
    <%= f.input :age %>
    <%= f.input :sex %>
    <%= f.input :sn %>
    <%= f.input :used_at %>
  </div>

  <div class="form-horizonta">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>用户列表</h1>
  <%= link_to "全部", users_path %>
  <%= link_to "已使用", users_path(used: :true) %>
  <%= link_to "未使用", users_path(used: :false) %>
  <%= link_to "一个月以上未使用", users_path(used: :one_month_after) %>
  <div class="table-responsive">
    <table class="table table-bordered table-striped table-hover">
      <thead>
        <tr>
          <th>手机号</th>
          <th>年龄</th>
          <th>性别</th>
          <th>序列号</th>
          <th>创建时间</th>
          <th>使用时间</th>
          <th colspan="3">操作</th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr class="<%= user.used_at ? 'success' : '' %>">
            <td><%= user.mobile %></td>
            <td><%= user.age %></td>
            <td><%= user.sex %></td>
            <td><%= user.sn %></td>
            <td><%= user.created_at %></td>
            <td><%= user.used_at %></td>
            <td><%= link_to 'Show', user %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="row">
    <div class="col-xs-9">
      <%= link_to 'New User', new_user_path, class: "btn btn-default btn-sm" %>
    </div>
    <div class="col-xs-3 text-right">
      <%= paginate @users %>
    </div>
  </div>

</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @user.mobile %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @user.sex %>
</p>

<p>
  <strong>Sn:</strong>
  <%= @user.sn %>
</p>

<p>
  <strong>Used at:</strong>
  <%= @user.used_at %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>